# Generated by Django 3.0.8 on 2020-08-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mriadmin', '0002_class_room_exam_marks_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
